### ISSUE TITLE
Background turns white in RES night mode

### ISSUE THREAD

**Issue by tstrass** [richmondwatkins/RedditCommentCompanion#2]
Description: The background of the div containing the post turns white, and the background of the comments window is white. It is especially hard to read, because the text in the comments window is light gray.

To reproduce: Open reddit with RES on. Turn on the RedditCommentCompanion setting to "Auto-open with RES". Hover cursor over a comments link.

I believe this is due to a recent RES update.

**Comment by richmondwatkins** [comment]
Thanks @tstrass. Yes this is due to the RES update. I'm working on a fix now.

**Comment by tstrass** [comment]
Much appreciated!

**Comment by richmondwatkins** [comment]
@tstrass just sent up and update. May take a little while to propagate google's store. Let me know if you have any issues.
